// This file is automatically generated.
// Please do not change this file!
export const about: string;
export const bar: string;
export const container: string;
export const content: string;
export const experience: string;
export const portfolio: string;
export const skills: string;
