// This file is automatically generated.
// Please do not change this file!
export const carouselContainer: string;
export const container: string;
export const description: string;
export const header: string;
export const projectName: string;
export const role: string;
export const slideContainer: string;
