// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const description: string;
export const details: string;
export const header: string;
export const projectName: string;
export const role: string;
