// This file is automatically generated.
// Please do not change this file!
export const button: string;
export const container: string;
export const message: string;
export const response: string;
export const show: string;
