// This file is automatically generated.
// Please do not change this file!
export const about: string;
export const active: string;
export const container: string;
export const experience: string;
export const navItem: string;
export const navList: string;
export const portfolio: string;
export const skills: string;
